if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	set(CMAKE_SYSTEM_NAME "Windows")
	set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM "windows+pe")
endif()

set(CMAKE_SYSTEM_PROCESSOR "X86")
set(CMAKE_C_COMPILER "i686-w64-mingw32-gcc")
set(CMAKE_CXX_COMPILER "i686-w64-mingw32-g++")
