set(VCPKG_TARGET_ARCHITECTURE "arm")
set(VCPKG_CRT_LINKAGE "static")
set(VCPKG_LIBRARY_LINKAGE "static")
set(VCPKG_ENV_PASSTHROUGH "PATH")

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../toolchains/arm.cmake")
