if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
	set(RUNTIME_SUBDIR "bin")
	set(LIBRARY_SUBDIR "bin")
	set(ARCHIVE_SUBDIR "lib")

elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	set(RUNTIME_SUBDIR "bin")
	set(LIBRARY_SUBDIR "lib")
	set(ARCHIVE_SUBDIR "lib")

	set(CMAKE_INSTALL_RPATH "$ORIGIN/../${LIBRARY_SUBDIR}")
endif()

## set build directories
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/${RUNTIME_SUBDIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/${LIBRARY_SUBDIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/${ARCHIVE_SUBDIR}")

## set install directories
set(RUNTIME_INSTALL_DIRECTORY "${RUNTIME_SUBDIR}")
set(LIBRARY_INSTALL_DIRECTORY "${LIBRARY_SUBDIR}")
set(ARCHIVE_INSTALL_DIRECTORY "${ARCHIVE_SUBDIR}")
